# Generated by Django 3.1.4 on 2020-12-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(help_text='Entre com o seu nickname', max_length=30)),
                ('texto', models.CharField(help_text='Digite a mensagem', max_length=100)),
                ('ipAddress', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Mensagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
