# Generated by Django 3.1.4 on 2020-12-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='Digite o ticker do ativo', max_length=10)),
                ('amount', models.IntegerField(help_text='Digite a quantidade a ser adicionada')),
                ('price', models.DecimalField(decimal_places=2, help_text='Digite o preço de compra', max_digits=10)),
                ('date', models.DateField(help_text='Digite a data de compra DD/MM/AAAA', verbose_name='Data de Compra')),
            ],
        ),
    ]
