# Generated by Django 3.1.4 on 2020-12-03 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='Digite o ticker do ativo', max_length=10)),
                ('amount', models.IntegerField(help_text='Digite a quantidade a ser adicionada')),
                ('price', models.DecimalField(decimal_places=2, help_text='Digite o preço de compra', max_digits=10)),
                ('date', models.DateField(help_text='Digite a data de compra DD/MM/AAAA', verbose_name='Data de Compra')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
